[package]
name = "stackulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"
rand = "0.8.5"
rustyline = "10.0.0"
crossterm = "0.25.0"
